version: '3.9'

services:
  db:
    image: postgres:alpine3.18
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    container_name: yandex_db
    networks:
      - yandex
    ports:
      - "5433:5432"

#  app:
#    build: app/
#    ports:
#      - "8888:8888"
#    restart: unless-stopped
#    container_name: yandex_app
#    depends_on:
#      db:
#        condition: service_healthy
#    networks:
#      - yandex

networks:
  yandex: