version: '3.9'

services:
  db:
    image: postgres:alpine3.18
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    container_name: yandex_db
    networks:
      - yandex_net

  redis:
    image: redis:alpine3.17
    restart: unless-stopped
    container_name: yandex_redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - yandex_net

  app:
    container_name: app
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - yandex_net

networks:
  yandex_net:
